[2021-07-12 14:58:25,137] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: maintest.testtask 2021-07-12T14:58:21.929866+00:00 [queued]>
[2021-07-12 14:58:25,284] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: maintest.testtask 2021-07-12T14:58:21.929866+00:00 [queued]>
[2021-07-12 14:58:25,285] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-12 14:58:25,287] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-12 14:58:25,301] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-12 14:58:25,344] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): testtask> on 2021-07-12T14:58:21.929866+00:00
[2021-07-12 14:58:25,385] {standard_task_runner.py:52} INFO - Started process 4949 to run task
[2021-07-12 14:58:25,419] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'maintest', 'testtask', '2021-07-12T14:58:21.929866+00:00', '--job-id', '36', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/tablecreation.py', '--cfg-path', '/tmp/tmps6gin3y0', '--error-file', '/tmp/tmp93q7v92g']
[2021-07-12 14:58:25,427] {standard_task_runner.py:77} INFO - Job 36: Subtask testtask
[2021-07-12 14:58:25,809] {logging_mixin.py:104} INFO - Running <TaskInstance: maintest.testtask 2021-07-12T14:58:21.929866+00:00 [running]> on host f29b1d03ad56
[2021-07-12 14:58:26,104] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=maintest
AIRFLOW_CTX_TASK_ID=testtask
AIRFLOW_CTX_EXECUTION_DATE=2021-07-12T14:58:21.929866+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-12T14:58:21.929866+00:00
[2021-07-12 14:58:26,501] {python.py:151} INFO - Done. Returned value was: None
[2021-07-12 14:58:26,588] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=maintest, task_id=testtask, execution_date=20210712T145821, start_date=20210712T145825, end_date=20210712T145826
[2021-07-12 14:58:26,841] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-12 14:58:26,894] {local_task_job.py:151} INFO - Task exited with return code 0
