[2022-01-06 13:11:20,183] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.restart_test 2022-01-06T13:10:54.506620+00:00 [queued]>
[2022-01-06 13:11:20,207] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.restart_test 2022-01-06T13:10:54.506620+00:00 [queued]>
[2022-01-06 13:11:20,208] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 13:11:20,209] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-01-06 13:11:20,210] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 13:11:20,238] {taskinstance.py:1087} INFO - Executing <Task(TriggerDagRunOperator): restart_test> on 2022-01-06T13:10:54.506620+00:00
[2022-01-06 13:11:20,253] {standard_task_runner.py:52} INFO - Started process 717 to run task
[2022-01-06 13:11:20,259] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'psotgrressdftest', 'restart_test', '2022-01-06T13:10:54.506620+00:00', '--job-id', '2226', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/POSTGRESRSERS.py', '--cfg-path', '/tmp/tmpi8phigim', '--error-file', '/tmp/tmpk30rw8l_']
[2022-01-06 13:11:20,260] {standard_task_runner.py:77} INFO - Job 2226: Subtask restart_test
[2022-01-06 13:11:20,336] {logging_mixin.py:104} INFO - Running <TaskInstance: psotgrressdftest.restart_test 2022-01-06T13:10:54.506620+00:00 [running]> on host 04be2259e97a
[2022-01-06 13:11:20,445] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=psotgrressdftest
AIRFLOW_CTX_TASK_ID=restart_test
AIRFLOW_CTX_EXECUTION_DATE=2022-01-06T13:10:54.506620+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-06T13:10:52.454471+00:00
[2022-01-06 13:11:22,493] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=psotgrressdftest, task_id=restart_test, execution_date=20220106T131054, start_date=20220106T131120, end_date=20220106T131122
[2022-01-06 13:11:22,529] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-06 13:11:22,583] {local_task_job.py:151} INFO - Task exited with return code 0
