[2021-07-21 11:34:01,609] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.restart_test 2021-07-21T11:32:45.610678+00:00 [queued]>
[2021-07-21 11:34:01,863] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.restart_test 2021-07-21T11:32:45.610678+00:00 [queued]>
[2021-07-21 11:34:01,865] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-21 11:34:01,866] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-21 11:34:01,867] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-21 11:34:01,993] {taskinstance.py:1087} INFO - Executing <Task(TriggerDagRunOperator): restart_test> on 2021-07-21T11:32:45.610678+00:00
[2021-07-21 11:34:02,019] {standard_task_runner.py:52} INFO - Started process 1190 to run task
[2021-07-21 11:34:02,028] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'psotgrressdftest', 'restart_test', '2021-07-21T11:32:45.610678+00:00', '--job-id', '1956', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/POSTGRESRSERS.py', '--cfg-path', '/tmp/tmplfl7ts6a', '--error-file', '/tmp/tmpgqqmv059']
[2021-07-21 11:34:02,030] {standard_task_runner.py:77} INFO - Job 1956: Subtask restart_test
[2021-07-21 11:34:02,356] {logging_mixin.py:104} INFO - Running <TaskInstance: psotgrressdftest.restart_test 2021-07-21T11:32:45.610678+00:00 [running]> on host 5795a622f846
[2021-07-21 11:34:02,576] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=psotgrressdftest
AIRFLOW_CTX_TASK_ID=restart_test
AIRFLOW_CTX_EXECUTION_DATE=2021-07-21T11:32:45.610678+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-21T11:32:41.001426+00:00
[2021-07-21 11:34:09,311] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=psotgrressdftest, task_id=restart_test, execution_date=20210721T113245, start_date=20210721T113401, end_date=20210721T113409
[2021-07-21 11:34:12,906] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-21 11:34:12,943] {local_task_job.py:197} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-07-21 11:34:12,951] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 1190
[2021-07-21 11:34:12,962] {process_utils.py:66} INFO - Process psutil.Process(pid=1190, status='terminated', exitcode=0, started='11:34:01') (1190) terminated with exit code 0
